version: 2

sources:
  - name: overture_april
    meta:
      external_location: 's3://overturemaps-us-west-2/release/2024-04-16-beta.0/theme=buildings/type=building/*'
    tables:
      - name: 2024-04-16-beta.0
  - name: overture_jan
    meta:
      external_location: 's3://overturemaps-us-west-2/release/2024-01-17-alpha.0/theme=buildings/type=building/*'
    tables:
      - name: 2024-01-17-alpha.0